version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: always
    volumes:
      - .:/home/user/app
    ports:
      - "3000:3000"
      - "5555:5555"

networks:
  metrics:
    driver: bridge
